# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # 인증서 및 프로비저닝 프로파일 관리
    # 실제 사용 시 Match 설정 필요
    # match(type: "appstore")
    
    # 앱 빌드
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )
    
    # TestFlight에 업로드
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # 인증서 및 프로비저닝 프로파일 관리
    # match(type: "appstore")
    
    # 앱 빌드
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )
    
    # App Store에 업로드
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      skip_app_version_update: true,
      force: true,
      submit_for_review: false
    )
  end
end 